### ISSUE TITLE
Is there a timeline for releasing the code?

### ISSUE THREAD

**Issue by wzzheng** [YiF-Zhang/RegionProxy#1]
Hello! Thanks for this great work. I like it very much. I was just wondering when do you plan to release the code?

**Comment by YiF-Zhang** [comment]
Thank you for your interest. Actually I'm in quarantine right now and having no access to some of the resources. I'll public the code and models as soon as possible. I think it won't be later than mid April.

**Comment by wzzheng** [comment]
Thanks for the reply! Looking forward to it.
