### ISSUE TITLE
AttributeError: 'PatchEmbed' object has no attribute 'DH'

### ISSUE THREAD

**Issue by hollow-503** [YiF-Zhang/RegionProxy#2]
亲爱的作者你们好，非常感谢你们的贡献！
我在运行 test.py 时遇到了如下的错误：

>   File "/home/disk/xxx/git/RegionProxy/models/vit.py", line 113, in forward
>     x, hw_shape = self.patch_embed(inputs), (self.patch_embed.DH,
>   File "/home/xxx/anaconda3/envs/region_proxy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'PatchEmbed' object has no attribute 'DH'

我运行的参数为：

> --config configs/regproxy_cityscapes/regproxy-s16-sub4+implicit-mid-2+768x768+80k+adamw-poly+cityscapes.py
> --checkpoint checkpoints/regproxy-s16-sub4+implicit-mid-2+768x768+80k+adamw-poly+cityscapes.pth
> --eval mIoU

以下为我的文件目录结构：

├── checkpoints
│   └── regproxy-s16-sub4+implicit-mid-2+768x768+80k+adamw-poly+cityscapes.pth
├── configs
│   ├── _base_
│   │   ├── datasets
│   │   ├── default_runtime.py
│   │   ├── models
│   │   └── schedules
│   ├── regproxy_ade20k
│   │   ├── regproxy-b16-sub4+implicit-mid-4+512x512+160k+adamw-cr+ade20k.py
│   │   ├── regproxy-l16-sub4+implicit-mid-9+640x640+160k+adamw-cr+ade20k.py
│   │   ├── regproxy-r26-s32-sub4+implicit-mid-n1+512x512+160k+adamw-poly+ade20k.py
│   │   ├── regproxy-r50-l32-sub4+implicit-mid-n1+640x640+160k+adamw-cr+ade20k.py
│   │   ├── regproxy-s16-sub4+implicit-mid-4+512x512+160k+adamw-poly+ade20k.py
│   │   └── regproxy-t16-sub4+implicit-mid-4+512x512+160k+adamw-poly+ade20k.py
│   └── regproxy_cityscapes
│       ├── regproxy-b16-sub4+implicit-mid-2+768x768+80k+adamw-cr+cityscapes.py
│       ├── regproxy-l16-sub4+implicit-mid-5+768x768+80k+adamw-cr+cityscapes.py
│       ├── regproxy-s16-sub4+implicit-mid-2+768x768+80k+adamw-poly+cityscapes.py
│       └── regproxy-t16-sub4+implicit-mid-2+768x768+80k+adamw-poly+cityscapes.py
├── data
│   └── cityscapes
│       ├── gtFine
│       ├── leftImg8bit
│       ├── test.txt
│       ├── train.txt
│       └── val.txt
├── LICENSE
├── models
│   ├── __init__.py
│   ├── proxy_head.py
│   ├── segmentors.py
│   └── vit.py
├── README.md
├── test.py
├── train.py
└── utils
    ├── checkpoint.py
    ├── __init__.py

**Comment by YiF-Zhang** [comment]
Hi @hollow-503 , please ensure that you are using the exact version of mmsegmentation, i.e. 0.17.

The error is probably due to a [change](https://github.com/open-mmlab/mmsegmentation/commit/85227b46c7b5eea82651e23e55f11cce33275298#diff-6d7e125f86d6374ae201f8f99904a283ead7523ac26ed64677218bceaa05a1b0R183-R204) of API from mmsegmentation.

**Comment by hollow-503** [comment]
Thank you for your reply! It works when i using mmsegmentation==0.17
