### ISSUE TITLE
About Region Encoder

### ISSUE THREAD

**Issue by wanghr-git** [YiF-Zhang/RegionProxy#4]
Hi,YiF.I have read the literature with reference to your open source code in the past two days, and have the following questions about the Region Encoder part:
1. H^W=N, then N is the number of tokens, do h and w change with the changes of H and W?
2. For a 512^512 image, H^h=512, W^w=512?
3. h and w are both 4 in your source code, so for a 512^512 image, H=W=128 and N=16384, is that too much?

**Comment by YiF-Zhang** [comment]
Hi @wanghr-git , 
1. In fact H and W never change (for a specific model), h and w can be changed to adjust output resolution;
2. In the default setting, we do not output the full resolution segmentation map, which I believe is a common practice of the community. e.g, for RegProxy-Ti/16, we set `H = W = 512 / 16 = 32` and `h = w = 4`, then the output is of `Hh * Ww = 128 * 128`.
3. Hence, H and W are not large numbers. The output resolution is decided by h and w. Moreover, increasing h, w (to increase output resolution) only introduce very little overheads (see Table 8 in appendix), enabling our model to produce arbitrarily fine output with limited cost.

**Comment by wanghr-git** [comment]
> 

Thank you for your reply! Best wishes!
