### ISSUE TITLE
About the handle borders

### ISSUE THREAD

**Issue by GuoQingqing** [YiF-Zhang/RegionProxy#6]
Hi, thanks for your code!  There are some about  handle borders in your code.  And I'm not very clear on the purpose of this. Could you please explain that?  Thank you very much!

**Comment by YiF-Zhang** [comment]
Hi @GuoQingqing, as described in Section 4.2, we distribute each pixel to its nearby (3*3) tokens to form regions. For pixels near the image borders, some of the tokens they should be distributed to may not exist (e.g., the top tokens are missing for pixels near the top image border), hance we set the corresponding probabilities to zero. To achieve this, we set those affinity predictions to `-inf` before softmax, as in [these lines](https://github.com/YiF-Zhang/RegionProxy/blob/76fea9b732af22f73aca129f1a2284d6e0fc2953/models/proxy_head.py#L51-L54).
